### ISSUE TITLE
Bug: Incompatible with` in-source:false` configuration

### ISSUE THREAD

**Issue by youngkidwarrior** [zth/rescript-relay-router#144]
The Vite Plugin has a hardcoded dependency on files being in source. This makes it impossible to use the `in-source: false` package spec

```
import { runCli } from "../cli/RescriptRelayRouterCli__Commands.mjs";
import { transformManifest } from "./RescriptRelayVitePlugin__ManifestTransform.mjs";
```

https://github.com/zth/rescript-relay-router/blob/af5487a81e5143477fe6c1020d13fbdd549ead5b/packages/rescript-relay-router/vite-plugins/RescriptRelayVitePlugin.mjs#L8

**Comment by tsnobip** [comment]
this also prevents using any other extension than `.mjs`. Converting this file to rescript should fix both issues :)

**Comment by zth** [comment]
This should be fixed in the latest versions. Reopen if still a problem.
