### ISSUE TITLE
[feature] make it compatible with rewatch

### ISSUE THREAD

**Issue by tsnobip** [zth/rescript-relay-router#154]
Right now the vite plugin depends on [reading `build.ninja`](https://github.com/zth/rescript-relay-router/blob/7a2a876017bde80c9cb34ca8031cf472ecbd2b6a/packages/rescript-relay-router/vite-plugins/RescriptRelayVitePlugin.mjs#L21) which is not generated by rewatch.

This is just a reminder.

**Comment by zth** [comment]
It'd be good to investigate if that reading is actually needed still. IIRC at least one part of that was eliminated with the dynamic import support shipping in ReScript.

**Comment by zth** [comment]
Kina solved in https://github.com/zth/rescript-relay-router/commit/3e32028bf437d79cd010173fd5cf691c4c2346ef
